language: node_js
node_js:
- node
- '7'
cache:
  directories:
  - web/elm-stuff/build-artifacts
  - web/elm-stuff/packages
  - web/sysconfcpus
before_install:
- openssl aes-256-cbc -K $encrypted_a0e672a7d53d_key -iv $encrypted_a0e672a7d53d_iv
  -in sshkey.enc -out sshkey -d
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- cd webserver && npm install && cd ..
- cd lambda && npm install && cd ..
- cd web
- npm install -g elm
- elm package install --yes
- |
  if [ ! -d "$TRAVIS_BUILD_DIR/web/sysconfcpus/bin" ];
  then
    git clone https://github.com/obmarg/libsysconfcpus.git;
    cd libsysconfcpus;
    ./configure --prefix=$TRAVIS_BUILD_DIR/web/sysconfcpus;
    make && make install;
    cd ..;
  fi
- cd ..
script:
- cd webserver && npm test && cd ..
- cd web && $TRAVIS_BUILD_DIR/web/sysconfcpus/bin/sysconfcpus -n 2 elm-make Main.elm
  --yes --output=index.html && cd ..
services:
- redis-server
env:
  global:
  - secure: F9aDYSzpeTKqaYSLuf0lsrkiUBwWhblf5Fgo9D7ks/F9elyNdbUjDkox4v/WF+LZr7wTl/BA2b1y1UCZYui7haDkTM4zDkpVt+dbCz6H2388yc/8tUOJ6giywtwY6jYEOqht61D6s0BygkFeGdc0XFyj22bqjuOBsKlvaSTyK3xMJ45F/kfyz+MeAWaAh1wceZtijljcqOkHx+ruConxdGELpmyfMAlYGXcuKlZe6XPxj/aDwkecsmlLFXV+dDzbtqbAXDvTBii20beIcArRWjSKDQAL0A4hbByAiIKGGVJKtQxMvWVel+HzrmIo1XmtlBjZCp1ANDW+YgMLyOFLVxgr496Fw8RaDk/DF2t6rXKsbCqBEllGtcbVvWY7i9dVePts8/EDEQnxI93mTwYfBRd9PqB8SY9j/iMGU+3T9s70oThy9xGwDOwveoNZnza1Ln6d8+GWwBjCWhnu4i121ubcHXg15OVVd2GLS0Y/ebnL3vPJeSHelI5mlH/saHAP9lZ5zs9wq++Cs0tBCxwibRxODneWjyUhFjAdOWnMUKk8khnmgpFItEPu56jCvikfa+I46wnCkOPdxqRV8sJX/A3li00R+IWW3kaUL8j9DC3+zX6nArpNQiWCBkA+Vxx1FD9YS8+vDDd2WNTo6vNsXpNJlygIvJ1+zxUrAfyXDsI=
  - secure: bwZWlqsdmBPUK0+Ge/k/eh0k8bGKdn+VDgtmL2UsZtAw0JDw648vlD44GjnZ9hYBxM5t3f28NzxOsl42jakPBcaXgXIyUqVtsCHzdYxDixJclcl3yIs6zRXjH2iRXJcWRZ+x/Muo961vGNSQ9tJLf0a+ydP0GkJa0Pu9CnMYo3bgZaOyxEnmQUzvhnD+LFaEyqwKvw3ej2OBGkjmhjWmur2doCCbmNfAA77Vqbe+OZD/UlzPqg3DcLYjIvP0anY12q8TrJbu+46l5KgYFPH8GqVs1yyRlwGAxEYWJtT2S1bJ+qqyopcUU3X5sdnFl0uk785dzExGr4o3W5uNQ0WrILQmSbMqFyEtOXCaVSpbfbMNTFA5LA8cADs2gL7gvYBXy0Dn8VtU5h+z9Ots6x6D0H+kQIqHizy57sq6MWcz9NNqPKVuVoOz+Gqdr/nTZif8lMv9FbECw9r79IbUjWNaQ3HOth/2y7WM8lgtO0sAyJg8Tn47UlR4HYxfPMpvNm4fLAkM653oq5HftkUhdN0fClxYq61pZQGRisKuN15fRCvgoqQTvA2OtZ7Xc/bEJsBvzx7HLqhXXtY3wZNY1gQUkBzEMgYvGHsKdUKtUElLrtMmT70NwMacuplainGmHBBBzJwhWYbRiREIrezvdtZhtweUQiAA+Y9GfF9yuOoZd4Y=
  - secure: zNf3opZu4l+VQ+NRhvm8tnWP06EF+y2wRraXGA2ru6YFR+6GghCkUEWs+IREa1L0rc3Bt3rtlZZLN/ld0ZtjuUciR2JWm2zVbwowI1oC/jRW+DGvtKNUUfcc1D3KZH8TWMLv/9xZmIPr968WefDWcmObIQDg6luK/EHwJH51iwPcQN31wKKbu1+EeqQTOxXD+DWLvNBNZmimVXZ1vTLFyEmNPzL5Lm1z+cZrhEqFtIrAXLjtOCnIj6XFT8ovqb6V1JItX7/ETTjy1ROIj+ylFA5CPPYHCCSyxeSVVd+eHRd+Ld9Xi53DOvw50/7y+bKpwRCkw1KMzXHoJzaoogAITlg0o0eo7W1z0rx/CLnonqmbCCJviYzwDTnYhtstFOgcAFvTVS6G8BhHizjTZspZEMsc+vdg2TOizJhI+zD7Ranc/CRQMm884kzqqCh89wHsV2VSMUASA2w7gLVELiuBqgvSK2RD2Vo7Ykj16LINwtNWBiHqdSgU+OksaK45H495yId7773MRJn4D7DmvhVngfA7MgswT+khBA1LhP7Kkk9YY14MSIi067//lzg982dE6A9ccOsAxZ2HaeUF83cWQD42OSFT24muVpOUrp1rKJCOGbtnLKkWES1rNMY0uJZFTkoFDGCLadhQ3ev0T7SoGBMbQ0dHcTW+zsGidCNm3cI=
  - secure: dgEhdlWSCLKH9c+nc/YnT4MLAW1unQsV5HtHwIWqHOOfQ768nvAP4gHxcAXMmDWQGfdZwUHttmqzvI/7aPJ6Y4+VbFKTTeW7L3ckjrbgjAKFNIU5sI3AieVHIq1CHCBloPIU5REhPTf1ttlnCMS4BTgYLBrbs22xg6/4jo08XgSXyh/VXJWl0zAApAdwubaBJjSCA9hGxiw5SZ7u1Atv2PVJRGO8VuOitiPeTCaSaqPsLtKwqQMnCsCWoJiOOEmub8L8RzackMUpI7rXYadCLyjn1iX4y+hIvUyokxD1dRMx9yX1ugiHzX3Eo+zesm/IfySF2+BoKTwq5VabbznK87MoXpXHxx+YqKkEdda2G0gsNUvFms58kPvj6zTN6enJ0W0+tvNKL6pDlZGOK0ryWvfZvnQJr/BDZV1aOfVewhzXd4PQyNlBv+9UBtYODFUOrW0da5dvOASQmW+o5h/IlBg0NuIaxE4Y7u2M20LqhN9PX/92BUWS1E8woirE5UQGhNuffV03oSthVEwzaflCXCZ18Aui9D0xEsf+cI2lY4bfdZclOS5tTyy4P/Mp4nSjd8ViWNNBSuR48NrZmiy1URnI+ANMsEShplThr36Fp++FW59T1pI8JNqogXt5sWhehqQHwc5qTZ4PNKvDwNkkqngUJpnr8XUK94xg28ypcdA=
  - secure: KJDKqW6ntQltVtMLkLEbfJQ3Y3rL50MBa+RC7RbHjnCxMBjnJPsnKJ+hI102v9hPojogKMtNcSv91F7c+Sm8H9anEGFvz9N0G4+sXHmDbGnomhrCImHijziAN7iDYlA3w96yos/PXDCw/tudULuZRSmvE7MAAvGFvyzNZyQ7Qn5OPOpRwaNY8yGcfXgx9e+2OXvYsz87OmWBHZr3reE8lTEgLHtvGIyXSqxVWwi8Bn/h+SSeFiPwoVqv8tW4adsRzBFNpk0uh7zUJAY4mTbkjBxX2zVepFKPXaPQZCPxFMmBaohTPLMSdX/+Kcla01xBTYO+LOa/0VC5vz6X3oSNu1VXGF8yYdeZ4dP1xi3X/0IDIR610AbmRUEQvax3fNdmVZDi4lSlqxTuxJoa074KsM6AcHfUtU5ziozi/fHzYur2Abcq/Wh8OIt5lc/PSAp7P/TLE+K9F+2rrEPKg/BL1POnJD40E8ErYfS74XSB1/+7132MootnmecZJUS882Jn4INaqGJTbnPQ15+hTxZvl6yYQjpZssD0OLXCa1XIWPDinZIVlDDQucxrINSP0vuxTMP+UrJHWJcRVd6Ht5naNgDY0dt9ag3ZJddyRxPTFZQQ8vSSXe84EZxXGVZ3zVVsplbushc7IxwdIG57s2crfWgn47xw93Pw9elCyRSM5WY=
  - secure: IX2tyZoA+BbUx7UJ8LnzgAMwkxhfT9PyC6rQih9bCzBkty1U8TNQcOznLNp1yX3z9JaJXUy7mARWW1tGgXLKF8UR6dZr8JQWvKXWD9+RrF19kSep7yeB0OBwE8Hh5IlyqqzyOikH7/t3r5k0ffn7xv/9NGC45hR2qHHBT++U3zv930NkXjgNcHrNWN27vrPAIal2AoP9XUvLzQWOmKhP9TZrb7lqjoKsScLYjIXKpZnSOnadVT+LecgLrKW4D6WyY+o64ZJiYyDQ+GrPyX0uq9jQFye5dNcXrfaPOWRV9NYM0zYwZ+S/fkuki5TskTSfpQg0yIYt0slQIHZJ8vX9I/X9B1kH4QEISheDgtsR9vyGxZuJ5E5UxBnj4XHIM1jRJuHw9dySUCQ+BBba/MK2gw8lpsBk67VLJdtPchxP0eNazG88Nmo0yTS2OdwK2Np2f24tEXpYBl4FmJhGohpeKtWGbwJuC2Ts3n1DI6mxJnBW+7NVEMJI6T79hu5Nqp1XrsWoCLWALvGfdoElsEZbrCCn8CcVYkvJkftE9ryUcB5+scRHjD63ll8TKB8Aozvljhjb63MNObdOct7MIiFhLGM537wdTe8QmaA9pti4MtroP5SqBUiN4MJZ+8sxQxzCiB82abejDu87nTmz9+TsbuupKNr8Jol4nyTpgmncbic=
  - secure: jNGWq9ltjLiOkg3LNJtl51rIWUCRWnKkFnLMxWxnHNGYGphRyV2sjB3vmqXCMubsptoXAPTFKbcaXsVgh05zT9PGyc5PJ/JzgQ+CZk5bZttGTeX+FAYAGTU3ekUVQcJggRAuW773KgVQOnohZ11cA2D1vBwDBFBN4gb/0FiEvH6V9xQw3c3nuMGjmCu6d5CBf3pXryKxs2LwR4XAoSAu/fPeIEVDmoaYs6OVk4iYzkolhZ3poo3up72Ns+C/n59jroMz2lSM7wQjAmI/F/ipzyQ2oPMJtHD+vzcuMdp47+nAxdfGOOQLZzzUEnEa2e7HmL/tmtwbI1WimWvz2dv0DS7VD+K9QN0rDrHoHdVE7vB0b/oCc1MJ7LLdfK+nKqy3VBOO59ZJzcZkCl/G2fSBnwlpVJrZFxQ5xpqCdBkutZ7I3AzXrWuazZ428gS2E4a2PDXhQynrAvJ5ZcwGzCY1mx0NZPyYPndDVFolp8mC/bLFUWNxfZ4J9uYnMTpKMDpWvCCkFO9nWGFNF1Rr/RGZspiLBXlMflLesgQi/RBFAYv4M9VvEJTSO+KwbMLDYGEoPR0Fz2fZCVwb4itmjA1Dubff38urxGKNwEj5uUvCOMl8O8diOPd9q545Mq1cuWcJJTZv/dNYDsdlr+Mwz/VCJCreW11E502/W2v0QbHgciI=
  - secure: J4lwPztbiaOGeHnyE5e7zl8ekuD8n7uZpvMPGVFHkzI2hI7ZlqNN3F2m/1np3BMJD7GjjK/MbciDdAHdJwAEtPmZk9skOboyRDKhysyx6RQg+E22lxC6UPmMTmoUaTFOrbgGAPW8eVTjd13URi1JIlsLVMyteE5m5axElFlOB+ZvbA+HgaeUHZiXk+d7VR6drbgpAOwR6dqtktrFojIHRv3ShM6ykbvIOah+dP98zfYwq9vJ5Ldutz9j0PFULD+IotuHdZf8qyqtphl1ks4kwhYJRbpKaE2q5sTvx6qzkakcZpKbKB3dZpsBb67ZXDmDdyOlsvRW7ysygkdAJllRxbpASUDnbMaqn6xSc0pYft3HIZFnLhlfARgBYlUM//ZjyfU11IHL5tjAzf+D9pfhtMBeavbNGoaVY8iBLvsNZjAvYJfVRAW8/Z/U8/Y5uIT3PNDnL1EE/sOUeBsL/sJ4AuO44LtsXNCyZQcW+IJoIGBwiRKEVCbLQ8RjKbOucJ2UAQtR2qHMVjEUM+O+fL0T9Uxlj2vcS5aNTm02nge81PArosxbIZn8TukEtHIMSwDR8yu3xPLq1ZHVMOrx8/pZkemYjy4X+whAy19kx4GufAvazWf7CNNph5GbZo/svg6xk/TG2dTLy/M3stuSIOizzqW1P6FSADXmvMI7io6XWIE=
  - secure: tQQVpmr3LF+Ro7JNW6jUEXNrEpnQ5fJUOeeYGTMeQ47HbUFDlPJfWoplN+g6J2lAMcNGU6H3o36B/C6X7JYQ2tZg/vY541RmVV2fiAs1exWGY5h3h+c5B+RGMDKDf9ITq8pSGgEpkYAbcNL5JCOGWEsNQHxxiNjXehUUV/GDW0y/+bY7Hblz+VMBf5f1BXuO8XBTa1XnGkqvn437MJBHolwQAlAc9+y4j9pByXWSY1znZhfh7gjhTjM2M0x76pjUkB5Sd/j7xSdP/l4yJ7MM8LXr3/lzUu2q4aQyuFNJDa1zWdQtd1CMtwrjA/I0f4c3Py2ou4rvRQ16JUoeawyl9O7zbTMcN35x/r/Ei98DL3yflY++Lgy6crOfvfNMZ9XqO8UnYutULC/ABuxSBNWnTSBBGsdImQ0vSAEZpItaSJ52CmWgct3gZs8N2ZzIxfRn92qjGYVzvzgly8BhMXaHd3wJD9eplCw2mOyawxU9rXqxCoKwdevLCHXqsLQYLt517lLU504YjD+ZJunxQYg94o6vgfsYDgZjfs7zJ/31DVpa0+RshPkVCXZS53gA4Ugei4t8Nx1UWMSLmV2Oo/yjJNrdSOEdACvzVXp295n6aIu96hVHiSFOrJtmJz83HmpR6SGjeU1xc6JQRydmkMqfAfc4St1TQ8NwVRleSjWXDYY=
  - secure: M+SonMzg2i05+SmqOLB/mn2S1ERJOkrT2zMewYlO0vAxr8u8QfMr653ypmB14tTE58rdg4oRb4Hq+QrjsTkz8GKT0BT2scahHXufaxc6VF+VouJrUoyHEdO93vsCcELm9Nk9QmtQmTC0skWjZupJ2R+CGp7aGeae27PPVVLEnlJ77QQuGNCNAHqeA5CCWDQvd3eq6qACdheoZpDpdH3BYRd1/lN7WHalWze+W2wLJGTbDbEPv8NykBi+R2Rlv7aRgPZwhIlOuv81xPNdupkuHNvVQe156jeYTwZAPie42/GKXy1bfNyiYcyg/y2xAnvnCsCQcxa4laQY1pcedUClD54nNG4FDMj/NP8N1qIOyvlXVchnymmK77t0TBtCRYd4uLF4x4bn68PKvg0PtD6UZeenNGwfjclOanzjQdIQTRL1x7pB9YgZqB1TnYBo+/0+EuJGL+ohuTRBWuRy1keC1Mbe6yBhaN4fRl+irz86I1Cb0QOIRoDMFVLpzfmwFI8+FtJnkEaFwhbWTkhp3RAl7QwdBSfFfEFpsOoc/dGvc9nGaif1v/Rbt+GmLqrdMRkSx5sWffr6PbNsw1lULKOu+duoMySqqWr8crcomaR5+q1+Pr8msKD9zPQR7Vgr/rHNxeCRD6ZTpuNuTsfS3RmZX1IXrBmVNA1WVYTQaOXraKg=
before_deploy:
- |
  if ! [ "$BEFORE_DEPLOY_RUN" ]; then
    export BEFORE_DEPLOY_RUN=1;
    cp web/index.html webserver/public/index.html

    ssh-agent bash -c 'ssh-add sshkey; git clone git@github.com:markusheilig/cloudy-secrets prod-env'
    cp prod-env/.env webserver/.env

    mkdir deploy
    zip --quiet -r "deploy/webserver--$TRAVIS_BRANCH--$TRAVIS_BUILD_NUMBER--$(date '+%Y-%m-%d--%H-%M-%S').zip" webserver
  fi
deploy:
- provider: s3
  access_key_id: AKIAJSKOWUWXRM2U473A
  secret_access_key:
    secure: JhB49loRKF6dEBx8tLRncCX7x5+UiO/tKXB30IcR6hoK4gL5Zg5HPT6Swq5OlfUU12LURs3WpHX314thNt8jmH6X1+/z8jLQbnNW9r8WxjjEsaS72NSbLiNyQTp4t6vy07q8P0FtpvNT7HUk+kgtbEIimc8D2ZpKJqTLgJD1azf1/sY/1rXqK5n0x4GHnlfNaioEVt9hQo3ss0b9C8xBdIybHbfNnlHago97Tj2t15bKw0zwUZggveyrN0t/onN5s5TuG3Ecym3SoYLVSPl5KZjWzigdr3jPwpfL9SSoB9Wm1w0c0O4A7/2u8MXNnlTNUXLHIOtxMYIlZ4S6E5mvdNyjBVIrZnXI88YTrE24If1zx5xHpgqqcwZ/mnaEprW2gaWMWDH5O9S8OTKEUhWPgbp0P9QyP9d3auk/D6FPaww0fOCvsUxiaORlcv8O4Im+IVwt1C0hKXWr6VUk66scLVd6Dqg8UH/6D6uWhXWYwa0HU/mmEQda0sBkOmALnIFtKggZXmdlvBEK8JLY2qcgiftBJM7iH+AjCsCYxPeSy6Om5LKW+pg+aka0GYMiToojWCOAJI0E/g1krvbs9U1g+GKKLDIiszgS0we/ZHde4zqd2ozjzHpxoZAJwYJB8v5z2oGv3rOhFSz5EWdWV3CexJ96Qb0jmgBunz2opprmvD0=
  bucket: cloudy-sentiment-analysis-2
  region: eu-central-1
  local_dir: deploy
  skip_cleanup: true
  upload-dir: webserver
  on:
    branch: master
    node: 7
- provider: lambda
  access_key_id: AKIAJSKOWUWXRM2U473A
  secret_access_key:
    secure: JhB49loRKF6dEBx8tLRncCX7x5+UiO/tKXB30IcR6hoK4gL5Zg5HPT6Swq5OlfUU12LURs3WpHX314thNt8jmH6X1+/z8jLQbnNW9r8WxjjEsaS72NSbLiNyQTp4t6vy07q8P0FtpvNT7HUk+kgtbEIimc8D2ZpKJqTLgJD1azf1/sY/1rXqK5n0x4GHnlfNaioEVt9hQo3ss0b9C8xBdIybHbfNnlHago97Tj2t15bKw0zwUZggveyrN0t/onN5s5TuG3Ecym3SoYLVSPl5KZjWzigdr3jPwpfL9SSoB9Wm1w0c0O4A7/2u8MXNnlTNUXLHIOtxMYIlZ4S6E5mvdNyjBVIrZnXI88YTrE24If1zx5xHpgqqcwZ/mnaEprW2gaWMWDH5O9S8OTKEUhWPgbp0P9QyP9d3auk/D6FPaww0fOCvsUxiaORlcv8O4Im+IVwt1C0hKXWr6VUk66scLVd6Dqg8UH/6D6uWhXWYwa0HU/mmEQda0sBkOmALnIFtKggZXmdlvBEK8JLY2qcgiftBJM7iH+AjCsCYxPeSy6Om5LKW+pg+aka0GYMiToojWCOAJI0E/g1krvbs9U1g+GKKLDIiszgS0we/ZHde4zqd2ozjzHpxoZAJwYJB8v5z2oGv3rOhFSz5EWdWV3CexJ96Qb0jmgBunz2opprmvD0=
  function_name: analyzeTweets
  zip: lambda
  region: eu-central-1
  role: arn:aws:iam::508323409197:role/lambda_basic_execution
  runtime: nodejs6.10
  handler_name: main.handler
  on:
    branch: master
    node: 7
